name: Build and Run hello_world.cpp with Makefile

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential clang-format

      - name: Build with Makefile
        run: make all

      - name: Run executable
        run: make execute

      - name: Format check
        run: make check

      - name: Clean build artifacts
        run: make clean
