name: Code coverage hello_world.cpp with Makefile

on:
  push:
    branches: [main]
    # paths:
    #   - '**.cpp'
    #   - '**.h'      
  pull_request:
    branches: [main]
    # paths:
    #   - '**.cpp'
    #   - '**.h'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential clang-format
          
      - name: Generate coverage report
        run: |
          cd cpp
          make clean
          make coverage              # compila con flags para cobertura
          ./hello            # ejecuta el binario para generar archivos .gcda
          gcov hello_world.cpp  # genera reporte .gcov basado en datos .gcda y .gcno
          ls
          cat hello_world.cpp.gcov  # muestra el reporte

      - name: Clean build artifacts
        run: |
          cd cpp
          make clean
