name: Python Coverage for hello_world.py (without real tests)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage pytest

      - name: Run dummy test to execute hello_world.py
        run: |
          cd python
          coverage run --source=hello_world -m pytest test_dummy.py
          coverage report
          coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: python/coverage.xml
          name: dummy-test-report
